"""add estado_feed_forward and audit_metadata columns

Revision ID: 326ff2789e2e
Revises: c8e1b3f90a21
Create Date: 2026-07-22 11:55:37.144100+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326ff2789e2e'
down_revision: Union[str, None] = 'c8e1b3f90a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('changelog', sa.Column('audit_metadata', sa.JSON(), nullable=True))
    op.add_column('submissions', sa.Column('estado_feed_forward', sa.String(length=50), server_default='PENDIENTE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'estado_feed_forward')
    op.drop_column('changelog', 'audit_metadata')
    # ### end Alembic commands ###
