"""feat(marco): add etapa column

Revision ID: 1ff2479bc0f8
Revises: 1f3dfc633a20
Create Date: 2026-07-19 10:06:15.931752+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff2479bc0f8'
down_revision: Union[str, None] = '1f3dfc633a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marcos_evaluacion', sa.Column('etapa', sa.String(length=10), server_default='BACH', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marcos_evaluacion', 'etapa')
    # ### end Alembic commands ###
