"""create profesores table

Revision ID: fed94eea19e8
Revises: bc073b1e73a7
Create Date: 2026-07-13 17:18:08.969484+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed94eea19e8'
down_revision: Union[str, None] = 'bc073b1e73a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesores_email'), 'profesores', ['email'], unique=True)
    op.create_index(op.f('ix_profesores_id'), 'profesores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profesores_id'), table_name='profesores')
    op.drop_index(op.f('ix_profesores_email'), table_name='profesores')
    op.drop_table('profesores')
    # ### end Alembic commands ###
